MAKE := make
PREFIX := /home/mathieu/opt/cross/x86_64-elf/bin/
CC     := $(PREFIX)x86_64-elf-gcc
LD     := $(PREFIX)x86_64-elf-ld


CFLAGS := -O0 -fno-inline -mno-red-zone -mgeneral-regs-only \
		  -I$(INCLUDE_DIR) -fno-omit-frame-pointer -fno-pie


