MAKE := make
CC     := $(GNU_PREFIX)x86_64-elf-gcc
LD     := $(GNU_PREFIX)x86_64-elf-ld


CFLAGS := -O0 -fno-inline \
		  -I$(INCLUDE_DIR) -I$(SDL2_BASE)/include -fno-omit-frame-pointer -fno-pie --freestanding -g

# CFLAGS += -march=native


LDLIBS :=$(SDL2_BASE)/libSDL2.a ../blibc/blibc.a
